name: get_trial.py
on:
  # push:
  #   branches:
  #     - main  # 替换为你的默认分支
  schedule:
    - cron: 0 10.40 0,1,12,13,14,15,16,17,18,19,20,21,22,23,24 * *
  workflow_dispatch:  # 触发手动事件
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DDAL_EMAIL: ${{ secrets.DDAL_EMAIL }}
      DDAL_PASSWORD: ${{ secrets.DDAL_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Prepare
        run: |
          sudo chmod 777 $CHROMEWEBDRIVER/chromedriver
          pip install requests beautifulsoup4 undetected-chromedriver ruamel.yaml
      - name: Run get_trial.py
        run: xvfb-run --auto-servernum python get_trial.py
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run king
        run: python kings.py  
   
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
           git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
          git pull --rebase
      - uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
      - name: Run get_trial_update_url.py
        run: python get_trial_update_url.py
